yolo_model:

  config_file:
    name: yolov2.cfg
  weight_file:
    name: yolov2.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - person
      - traffic light
      - fire hydrant
      - stop sign
      - bench
      - chair
      - sofa
      - toilet
      - refrigerator
      - vase

